### ISSUE TITLE
[不具合]WSL2上のDockerでのインストールでエラー

### ISSUE THREAD

**Issue by hiroshih** [thinkingreed-inc/F-RevoCRM#1005]
**概要（Overview）**
WSL2上のDockerでのインストールでエラーが発生し、正常にインストールが出来ません。
以下のようなエラーが発生しています。
何回かリトライしてみましたが同じ結果でした。

Fatal error: Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in /var/www/html/data/VTEntityDelta.php:54 Stack trace: #0 /var/www/html/data/VTEntityDelta.php(41): VTEntityDelta->fetchEntity('Users', 1) #1 /var/www/html/include/events/VTEventTrigger.inc(143): VTEntityDelta->handleEvent('vtiger.entity.a...', Object(VTEntityData)) #2 /var/www/html/include/events/VTEventsManager.inc(118): VTEventTrigger->trigger(Object(VTEntityData)) #3 /var/www/html/data/CRMEntity.php(1076): VTEventsManager->triggerEvent('vtiger.entity.a...', Object(VTEntityData)) #4 /var/www/html/modules/Users/Users.php(1107): CRMEntity->save('Users', '') #5 /var/www/html/modules/Users/models/Module.php(300): Users->save('Users') #6 /var/www/html/modules/Vtiger/models/Record.php(261): Users_Module_Model->saveRecord(Object(Users_Record_Model)) #7 /var/www/html/modules/Users/models/Record.php(155): Vtiger_Record_Model->save() #8 /var/www/html/setup/scripts/13_Update_Users.php(57): Users_Record_Model->save() #9 /var/www/html/setup/Setup.php(50): require_once('/var/www/html/s...') #10 /var/www/html/modules/Install/views/Index.php(225): include_once('/var/www/html/s...') #11 /var/www/html/modules/Install/views/Index.php(61): Install_Index_view->Step7(Object(Vtiger_Request)) #12 /var/www/html/includes/main/WebUI.php(226): Install_Index_view->process(Object(Vtiger_Request)) #13 /var/www/html/index.php(26): Vtiger_WebUI->process(Object(Vtiger_Request)) #14 {main} thrown in /var/www/html/data/VTEntityDelta.php on line 54

**再現手順（To Reproduce）**
不具合の発生手順を細かく記載してください。
（Steps to reproduce the behavior:）
1. WSL2上のUbuntu内で、git clone にてF-RevoCRMをクローン
1. docker compose upで起動
1. PHPのdockerコンテナ内でcomposerをインストール
1. IPアドレスでインストール画面にアクセスし、インストール実行
2. エラー画面が表示される

※一応アクセスは可能な状態になりますが、言語が英語と日本語が混在した状態になっています。（添付画像参照）
　言語設定は英語になっており、日本語に変えようとしても選択肢に出て来ないので変えることが出来ません。
![スクリーンショット 2024-04-15 105914](https://github.com/thinkingreed-inc/F-RevoCRM/assets/4231483/d4339304-496d-436f-831b-8963e966a2fc)

**稼働環境 Server (please complate the following information):**
- OS:Windows10
- Distro: Ubuntu 20.04
- Browser Edge

**Comment by hiroshih** [comment]
問題が発生するのはF-RevoCRMの7.4.0のときで、7.3.9の場合は問題ありませんでした。

**Comment by Remicck** [comment]
@hiroshih @junmt 

私の環境でも起きましたので共有します。
- docker php:8.3-apache
- 現時点でのmain

該当の修正コードはありますので、後ほどPR出します。

**Comment by hiroshih** [comment]
V1コマンド（docker-compose up）とV2コマンド（docker compose up）で挙動が変わるようなのですが、V1コマンドで起動するのが正しいのでしょうか。

**Comment by Remicck** [comment]
取り急ぎ `docker compose` コマンドであれば通るのですが、 `docker-compose` コマンドは未確認です。
また、 `docker-compose.yml` についても、Compose Specに合わせる形で、
- versionの廃止
- ファイル名を `compose.yaml` に変更
等行う必要がありそうです。
https://www.compose-spec.io/

**Comment by hiroshih** [comment]
ご確認ありがとうございます。
Readme.mdには「docker-compose up（V1コマンド）」で記載されているので、いつもそちらでやっていたのですが、「docker compose up（V2コマンド）」を想定されているということでしょうか。もう一度V2でやってみようと思います。

**Comment by Remicck** [comment]
@hiroshih 
現状 v2以外の環境がすぐにないので、もし対応できるのであればPR出していただけると助かります。

**Comment by breakthrough7** [comment]
こんにちは、どうぞよろしくお願いいたします。
先日、私も V1コマンドで作業を進めてしまい、結局エラーが出てまともに動作しないのでその環境を捨ててV2コマンドでF-RevoCRMのインストール画面でインストール開始しました。
しかし失敗してしまいます。エラー内容はこちらの件を最初に投稿された方と同じ内容のようです。　自己解決したくてやり直したりしたのですが手詰まりとなり投稿させていただきました。
続報やご助言いただけると幸いです。

Windows11Pro
WSL2（WSL バージョン: 2.2.4.0）
Ubuntu-20.04
Docker version 24.0.5, build 24.0.5-0ubuntu1~20.04.1
Docker Compose version v2.12.2

　　- - - - - - - - - -

F-RevoCRM Installation Wizardのエラーメッセージ（末尾を抜粋）
vtiger_project 2024-06-19 01:30:51 
vtiger_assets 2024-06-19 01:30:52 
vtiger_dailyreports 
実行が完了しました。
実行が完了しました。
実行が完了しました。
Start Script
Fatal error: Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in /var/www/html/data/VTEntityDelta.php:54 Stack trace: #0 /var/www/html/data/VTEntityDelta.php(41): VTEntityDelta->fetchEntity('Users', 1) #1 /var/www/html/include/events/VTEventTrigger.inc(143): VTEntityDelta->handleEvent('vtiger.entity.a...', Object(VTEntityData)) #2 /var/www/html/include/events/VTEventsManager.inc(118): VTEventTrigger->trigger(Object(VTEntityData)) #3 /var/www/html/data/CRMEntity.php(1076): VTEventsManager->triggerEvent('vtiger.entity.a...', Object(VTEntityData)) #4 /var/www/html/modules/Users/Users.php(1107): CRMEntity->save('Users', '') #5 /var/www/html/modules/User
[F-RevoCRM_Installation_Wizard_リロード時の更新後の画面内容_20240618.txt](https://github.com/user-attachments/files/15890357/F-RevoCRM_Installation_Wizard_._20240618.txt)
[F-RevoCRM_Installation_Wizard_20240618.txt](https://github.com/user-attachments/files/15890358/F-RevoCRM_Installation_Wizard_20240618.txt)
s/models/Module.php(300): Users->save('Users') #6 /var/www/html/modules/Vtiger/models/Record.php(261): Users_Module_Model->saveRecord(Object(Users_Record_Model)) #7 /var/www/html/modules/Users/models/Record.php(155): Vtiger_Record_Model->save() #8 /var/www/html/setup/scripts/13_Update_Users.php(57): Users_Record_Model->save() #9 /var/www/html/setup/Setup.php(50): require_once('/var/www/html/s...') #10 /var/www/html/modules/Install/views/Index.php(225): include_once('/var/www/html/s...') #11 /var/www/html/modules/Install/views/Index.php(61): Install_Index_view->Step7(Object(Vtiger_Request)) #12 /var/www/html/includes/main/WebUI.php(226): Install_Index_view->process(Object(Vtiger_Request)) #13 /var/www/html/index.php(26): Vtiger_WebUI->process(Object(Vtiger_Request)) #14 {main} thrown in /var/www/html/data/VTEntityDelta.php on line 54

**Comment by hiroshih** [comment]
@breakthrough7 
本件、RemicckさんがPR出して下さってますので、その内容を取り込めば正常に起動できます。
私の方では確認済みです。
お試しください。

**Comment by Remicck** [comment]
@breakthrough7 
https://github.com/thinkingreed-inc/F-RevoCRM/pull/1032
まだ取り込めてなくてすみません。
こちらの差分を当てて試してもらえますか？

**Comment by hasesho28** [comment]
#1032 にて、現状のmainではdockerでのInstallが可能とのことですので、こちらはCloseします。
