### ISSUE TITLE
[不具合]

### ISSUE THREAD

**Issue by KazukiShimada** [thinkingreed-inc/F-RevoCRM#779]
**概要（Overview）**
システム管理者のチェックが入っていないユーザでログインし、上部のメニューをクリックすると、以下のエラーが表示される
Fatal error: Uncaught Error: Call to a member function isCvEditable() on null in/var/www/F-RevoCRM-7.3.6/test/templates_c/v7/6ecadaf56111d9d8acba87da3e0ce295a3b4c992.file.ListViewContents.tpl.php:168 Stack trace: #0 /var/www/F-RevoCRM-7.3.6/libraries/Smarty/libs/sysplugins/smarty_internal_templatebase.php(180): content_63dc9cb342ac1() #1 /var/www/F-RevoCRM-7.3.6/libraries/Smarty/libs/sysplugins/smarty_internal_templatebase.php(374): Smarty_Internal_TemplateBase->fetch() #2 /var/www/F-RevoCRM-7.3.6/includes/runtime/Viewer.php(188): Smarty_Internal_TemplateBase->display() #3 /var/www/F-RevoCRM-7.3.6/modules/Vtiger/views/List.php(115): Vtiger_Viewer->view() #4 /var/www/F-RevoCRM-7.3.6/includes/main/WebUI.php(226): Vtiger_List_View->process() #5 /var/www/F-RevoCRM-7.3.6/index.php(20): Vtiger_WebUI->process() #6 {main} thrown in /var/www/F-RevoCRM-7.3.6/test/templates_c/v7/6ecadaf56111d9d8acba87da3e0ce295a3b4c992.file.ListViewContents.tpl.php on line 168

また、レポートアイコンをクリックすると、以下のエラーが表示される
Fatal error: Uncaught Error: Call to a member function FetchRow() on bool in /var/www/F-RevoCRM-7.3.6/include/database/PearDatabase.php:532 Stack trace: #0 /var/www/F-RevoCRM-7.3.6/modules/Reports/Reports.php(551): PearDatabase->fetch_array() #1 /var/www/F-RevoCRM-7.3.6/modules/Reports/models/Folder.php(97): Reports->sgetRptsforFldr() #2 /var/www/F-RevoCRM-7.3.6/modules/Reports/models/ListView.php(112): Reports_Folder_Model->getReports() #3 /var/www/F-RevoCRM-7.3.6/modules/Reports/views/List.php(181): Reports_ListView_Model->getListViewEntries() #4 /var/www/F-RevoCRM-7.3.6/modules/Reports/views/List.php(33): Reports_List_View->initializeListViewContents() #5 /var/www/F-RevoCRM-7.3.6/includes/main/WebUI.php(76): Reports_List_View->preProcess() #6 /var/www/F-RevoCRM-7.3.6/includes/main/WebUI.php(225): Vtiger_WebUI->triggerPreProcess() #7 /var/www/F-RevoCRM-7.3.6/index.php(20): Vtiger_WebUI->process() #8 {main} thrown in /var/www/F-RevoCRM-7.3.6/include/database/PearDatabase.php on line 532

**再現手順（To Reproduce）**
１．システム管理者でログインし、任意のユーザの設定から「システム管理者」のチェックをはずし、保存
２．ログアウトし、チェックをはずしたユーザでログイン
３．例えば、「マーケティング」->「キャンペーン」をクリック

**スクリーンショット（Screenshots）**
![f-revo1](https://user-images.githubusercontent.com/7901078/216564471-7061304c-8dbc-457a-85a9-c52a3bfb1ed2.png)
![f-revo2](https://user-images.githubusercontent.com/7901078/216564509-3e42e477-a0f9-40e4-90bc-68c073e92ce2.png)

**稼働環境 Server (please complate the following information):**
- OS: Ubuntu 22.04.1 LTS / WSL2 / Windows10 Home 22H2
- PHP version: PHP 7.4.33
- MySQL version:  MariaDB 10.6.11

**不具合発生時の利用ブラウザ Blowser(please complete the following information):**
- OS: 同上（同じPCのwindowsからWSL2のubuntuにアクセス）
- Browser: Google chrome
- Version: 109.0.5414.120（Official Build） （64 ビット）

**その他情報（Additional context）**

**Comment by Remicck** [comment]
@KazukiShimada ありがとうございます、確認します。

**Comment by KazukiShimada** [comment]
エラーの内容で検索すると、下記のページがありました。
https://discussions.vtiger.com/discussion/186050/v7-0-1-call-to-a-member-function-iscveditable
確認してみたところ、確かにvtiger_cv2roleとvtiger_cv2rsというテーブルは見当たりません。

 MariaDB [frevocrm]> select * from vtiger_cv2role;
--------------
select * from vtiger_cv2role
--------------

ERROR 1146 (42S02): Table 'frevocrm.vtiger_cv2role' doesn't exist
MariaDB [frevocrm]> select * from vtiger_cv2rs;
--------------
select * from vtiger_cv2rs
--------------

ERROR 1146 (42S02): Table 'frevocrm.vtiger_cv2rs' doesn't exist
MariaDB [frevocrm]>

今回はじめてのインストールでしたので、上のリンク先にある「There are 2 tables missing during Migration. 」には当たらないと思うのですが。
よろしくお願いいたします。

**Comment by KazukiShimada** [comment]
試しにリンク先のSQLを実行してテーブルを作成したところ、エラーは出なくなりました。
レポートの方には変化がないので、これとは関係がなさそうです。

**Comment by Remicck** [comment]
@KazukiShimada 
vtiger_cv2roleについては6系から7系に移行した際に追加されたテーブルのようです。
通常、インストールを行うとマイグレーションスクリプトも全て実行されて完了するはずですが、何かしらの理由で該当のテーブルが作成されていなかった可能性があります。

具体的には以下のプログラムから生成されています。
/modules/Migration/schema/660_to_700.php
```php
if (!Vtiger_Utils::CheckTable('vtiger_cv2role')) {
	Vtiger_Utils::CreateTable('vtiger_cv2role',
			'(`cvid` int(25) NOT NULL,
			`roleid` varchar(255) NOT NULL,
			KEY `vtiger_cv2role_ibfk_1` (`cvid`),
			CONSTRAINT `vtiger_customview_ibfk_3` FOREIGN KEY (`cvid`) REFERENCES `vtiger_customview` (`cvid`) ON DELETE CASCADE,
			CONSTRAINT `vtiger_role_ibfk_1` FOREIGN KEY (`roleid`) REFERENCES `vtiger_role` (`roleid`) ON DELETE CASCADE)', true);
}

if (!Vtiger_Utils::CheckTable('vtiger_cv2rs')) {
	Vtiger_Utils::CreateTable('vtiger_cv2rs',
			'(`cvid` int(25) NOT NULL,
			`rsid` varchar(255) NOT NULL,
			KEY `vtiger_cv2role_ibfk_1` (`cvid`),
			CONSTRAINT `vtiger_customview_ibfk_4` FOREIGN KEY (`cvid`) REFERENCES `vtiger_customview` (`cvid`) ON DELETE CASCADE,
			CONSTRAINT `vtiger_rolesd_ibfk_1` FOREIGN KEY (`rsid`) REFERENCES `vtiger_role` (`roleid`) ON DELETE CASCADE)', true);
}
```

URLのコードと微妙に違うところが気になりますが、意味合いとして同じであれば問題ないと思います。
ちなみにMariaDBのコンフィグで特別なものは設定していますか？

**Comment by Remicck** [comment]
@KazukiShimada 
本レポジトリにて共有されているDockerfileベースの環境では再現しないことを確認しました。
詳細なログがほしいので、以下の手順試していただけますか？

config.performance.php
```php
/* Performance paramters can be configured to fine tune vtiger CRM runtime */
$PERFORMANCE_CONFIG = Array(
	// Enable log4php debugging only if requried 
	'LOG4PHP_DEBUG' => true,
```

log4php.properties
```php
log4php.rootLogger=DEBUG,A1
```

適切な書き込み権限があれば、logs内にvtigercrm.log というファイルが生成されます。
かなりの量のログが流れるのでご注意ください。


ここからは未定なのですが、何かしらCREATE TABLE系の処理が色々コケてしまっている可能性を危惧しています。
念のためですが、Docker環境でインストール直後、ユーザーを1名追加した状態でのテーブルの総数は以下です。
```
mysql> show tables;
---
534 rows in set (0.00 sec)
```
ご参考までに・・・。

**Comment by KazukiShimada** [comment]
wsl2にインストールしたubuntu ltsのmariadbの次のコンフィグに、
/etc/mysql/mariadb.conf.d/50-server.cnf
以下の設定を行いました。
---------------------------------------------------------------------------------------------------------------
# This group is only read by MariaDB servers, not by MySQL.
# If you use the same .cnf file for MySQL and MariaDB,
# you can put MariaDB-only options here
[mariadb]
sql_mode=ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
default-authentication-plugin=mysql_native_password
---------------------------------------------------------------------------------------------------------------

config.performance.phpとlog4php.propertiesにつきましては、インストール直後にご指摘の設定を行いましたが、logsディレクトリはできていません。ubuntuのapache2は、www-dataというユーザで動いており、ルートディレクトリ配下のファイル／ディレクトリはwww-dataが所有者です。パーミッションは、ファイルは644、ディレクトリは755です。
apache2.confのディレクティブで、/var/wwwについてAllowOverride None -> Allに変更しましたが、特に変わりはありません。

こちらのshow tables;の出力は
mysql> show tables;
---
532 rows in set (0.002 sec)
2つのテーブルを追加した後の結果になります。まだ2つ足りません。;-)

一度dockerで試していまくいかなかったので、手動で環境構築->インストールで試してみたのですが、今ならdockerでうまくいかなかった理由がなんとなくわかりますので、再度docker版で試してみます。
ご返答ありがとうございました。

**Comment by KazukiShimada** [comment]
もしかすると別チケット切ったほうがいいのかもしれませんが、issueを増やしたくないのでここで書きます。
下記のリンク先を参照して、docker版を試してみました。
https://engineer.thinkingreed.co.jp/2020/12/16/f-revocrm%E3%82%92docker%E3%81%A7%E6%A7%8B%E7%AF%89%E3%81%99%E3%82%8B/
https://github.com/thinkingreed-inc/F-RevoCRM
https://github.com/thinkingreed-inc/F-RevoCRM/blob/main/docker/README.md
残念ながら、xdebugというののビルドに失敗します。

 => ERROR [5/5] RUN pecl install xdebug   && docker-php-ext-enable xdebug                                     4.4s
\------
 > [5/5] RUN pecl install xdebug   && docker-php-ext-enable xdebug:
#0 4.348 pecl/xdebug requires PHP (version >= 8.0.0, version <= 8.2.99), installed version is 7.4.33
#0 4.348 No valid packages found
#0 4.348 install failed
\------
Dockerfile:34
\--------------------
  33 |         docker-php-ext-install -j$(nproc) imap
  34 | >>> RUN pecl install xdebug \
  35 | >>>   && docker-php-ext-enable xdebug
  36 |
\--------------------
ERROR: failed to solve: process "/bin/sh -c pecl install xdebug   && docker-php-ext-enable xdebug" did not complete successfully: exit code: 1
ERROR: Service 'php' failed to build : Build failed

xdebugというのが、php8を求めるようになったかららしいです。
https://qiita.com/kumanobori/items/49b5515e0922799035ea
docker/php/Dockerfileを、下記のように書き換えて回避してます。

RUN pecl install xdebug-3.1.6 \
  && docker-php-ext-enable xdebug

一応お伝えしておきます。よろしくお願いいたします。

**Comment by Remicck** [comment]
@KazukiShimada 
ありがとうございます。xdebugは開発時のみに必要なのでコメントアウトしておいたほうがいいですね。
お手数ですがxdebug部分をDockerfileからコメントアウトするPRいただけませんか？

報告ありがとうございます、よろしくお願いします。

**Comment by Remicck** [comment]
php8対応については内部で進捗中なので、どこかでマージできれば・・・。

**Comment by KazukiShimada** [comment]
PR送りました。
まともにPRしたのは初めてなので、おかしなことになっていたらすみません。
